name: Reportar Incidencia / Desprotección
description: Utiliza esta plantilla para documentar una incidencia grave o falta de protección percibida en Wallapop.
title: "[INCIDENCIA] Breve descripción del caso"
labels: ["incidencia", "desprotección"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ### Gracias por compartir tu experiencia. 
        Tu reporte ayudará a la comunidad a conocer riesgos reales y servirá como base de datos de prácticas reportadas.
  - type: input
    id: producto
    attributes:
      label: Producto implicado
      description: Ejemplo: iPhone 13 Pro, Nintendo Switch, etc.
      placeholder: Escribe el producto aquí
    validations:
      required: true
  - type: input
    id: cuantia
    attributes:
      label: Cuantía económica (aprox.)
      description: ¿A cuánto asciende el perjuicio económico estimado?
      placeholder: Ejemplo: 450€
    validations:
      required: true
  - type: dropdown
    id: tipo-incidencia
    attributes:
      label: Tipo de incidencia / desprotección
      options:
        - Envio recibido roto y el seguro no cubre
        - Producto devuelto distinto al enviado (irregularidad en devolución)
        - Cuenta bloqueada con dinero en el monedero
        - Falta de respuesta soporte técnico (> 48h)
        - Incidencia con pago externo (bizum/transferencia)
        - Otro
    validations:
      required: true
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción detallada de los hechos
      description: Explica cronológicamente qué ha pasado.
      placeholder: El día X compré Y, al llegar estaba roto...
    validations:
      required: true
  - type: textarea
    id: respuesta-soporte
    attributes:
      label: Respuesta de Wallapop
      description: ¿Qué te han dicho desde soporte o el seguro?
      placeholder: Me dicen que el embalaje no era adecuado...
  - type: textarea
    id: pruebas
    attributes:
      label: Pruebas y evidencia
      description: Puedes pegar enlaces a capturas de pantalla (Imgur, etc.) o hilos de redes sociales.
      placeholder: Enlace a captura...
  - type: checkboxes
    id: terminos
    attributes:
      label: Confirmación
      options:
        - label: Confirmo que la información proporcionada es veraz y no contiene datos personales sensibles de terceros.
          required: true
